[package]
name = "pallet-example-mbm"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "Example FRAME pallet for multi-block migrations"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true }
pallet-migrations = { workspace = true }
frame = { workspace = true, features = ["experimental", "runtime"] }
log = { workspace = true }
scale-info = { workspace = true }


[features]
default = ["std"]
std = [
	"codec/std",
	"frame/std",
	"log/std",
	"pallet-migrations/std",
	"scale-info/std",

]
runtime-benchmarks = [
	"frame/runtime-benchmarks",
	"pallet-migrations/runtime-benchmarks",
]
try-runtime = [
	"frame/try-runtime",
	"pallet-migrations/try-runtime",
]
